### ISSUE TITLE
Immovable Rod not working

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#16593] opened 2022-10-02 13:43 UTC
Reporting client version: 514.1588

## Round ID:
6648

## Testmerges:
- [[MODULARIZING] Partial Refactoring of Organic Interface Code](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16019)
- [Cyborg Model Advertisement Update, or How I Stopped Having To Guess If You're A Janitor Or A Miner](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16468)
- [Space hotel Tender loving Care (and more)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16290)
- [Fixed species that don't have hunger, not having a stomach](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16574)
- [[MIRROR] Multiz Rework: Human Suffering Edition (Contains PLANE CUBE) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16472)
- [forging using material items, not rods](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16553)
- [[MIRROR] Bump byond up to 514.1588 [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16514)

**Comment by lessthnthree** [comment] 2022-10-02 21:23
Duplicate of #15793

**Closed as completed** 2023-01-18 01:20 UTC
