### ISSUE TITLE
Unable to spend quirk points

### ISSUE THREAD

**Issue by Istasha528** [Skyrat-SS13/Skyrat-TG#18512] opened 2023-01-04 19:03 UTC
## Round ID:
197604 According to sb.atlantaned.space/rounds

## Reproduction:
I was unable to spend my last two quirk points.  I have a single prosthetic arm for -1 and -5 from two other quirks: Heavy Sleeper and Depression, which should give me -6 total.
![image](https://user-images.githubusercontent.com/121973022/210629458-64ebd9b4-7a35-4325-8376-877ef5d35fad.png)
![image](https://user-images.githubusercontent.com/121973022/210630028-6c252c62-3c63-4780-a4ca-c559c3276be8.png)
![image](https://user-images.githubusercontent.com/121973022/210630093-d7a68417-7ecc-4598-b959-07536d17c6d8.png)

However, I am unable to spend the last two perk points on my desired perk: Hardened Soles.  I am able to select the perk, and it appears in the Current Quirks tab of the menu, though my quirk balance does not change when I do so.  It only updates based on slotting in Light Step.  Once the menu closes it removes Hardened Soles and I am left with the remaining perks I posted above.

A brief note:  while I am fairly certain this is the correct round ID, this bug has been consistent ever since character creation across multiple logins and two played rounds.

**Comment by RimiNosha** [comment] 2023-01-04 19:10
You seem to have one extra quirk point being gained from *somewhere*.

**Comment by Istasha528** [comment] 2023-01-04 19:10
Yes, I have a prosthetic arm that gives -1.  Sorry, thought I mentioned that.

**Comment by RimiNosha** [comment] 2023-01-04 19:11
Ah, then augments+ is broken again.

**Comment by Istasha528** [comment] 2023-01-04 19:11
Oof.  Dang if you all aren't quick on a bugfix, though.

**Comment by Floofies** [comment] 2023-01-05 02:46
I just got things to behave even weirder. By picking 2 prosthetic arms, adding 2 quirk points. I was able to pick multiple Quirks costing 2 points, but none of those selections seemed to reduce my total points. I was able to add quite a lot of Quirks this way.

![image](https://user-images.githubusercontent.com/17753498/210690216-3564bd73-298d-45a6-9f19-3fc0022d8277.png)

**Comment by Floofies** [comment] 2023-01-06 02:49
Caused by upstream PR #8153 wherein we forgot to add our Augment-specific code to `/datum/controller/subsystem/processing/quirks/proc/filter_invalid_quirks(list/quirks)`

I am making a fix for this issue now :)

**Closed as completed** 2023-02-14 02:18 UTC
Labels: Bug
