### ISSUE TITLE
The EMP Magazine dupe

### ISSUE THREAD

**Issue by ReynTheLord** [Skyrat-SS13/Skyrat-tg#7812] opened 2021-08-27 18:12 UTC
Reporting client version: 514.1561

## Round ID:
2830 of report, happened a different round

## Testmerges:
- [cortical borer](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7554)
- [venus changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7692)

## Reproduction:

So, while not reliable, I had my gun in my belt, my pistol, that is. In a peacekeeper belt, at max capacity. I got hit by a few EMPs, which would usually cause the mag to eject. It did, and didn't. I checked my belt while going to go cryo, and I found a mag in a slot in the belt which shouldn't be there. I assumed it was properly ejected, so I tried to put it back in the gun, and it... swapped out with a mag in the gun. I checked my ammo pouch, all my other mags were still there.  The mysterious fifth mag even had the same ammo count as the one in my gun, missing a bullet due to one being readied.

Its not reliable, but, it happened.

**Comment by tf-4** [comment] 2021-08-28 00:12
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/6957

**Closed as completed by tf-4** 2021-08-28 00:12 UTC
