### ISSUE TITLE
The AI can hear erp in Xenobiology despite never asking for this oh god please help

### ISSUE THREAD

**Issue by BurgerLUA** [Skyrat-SS13/Skyrat-tg#7250] opened 2021-07-30 03:37 UTC
## Round ID: 
2537

## Testmerges:
Round ID: 2538
BYOND Version: 514.1557
Server revision compiled on: 2021-07-29T09:40:56+00:00
Master commit: 7ed8f033eab6a8ff8b265f5c9db0202f5711c423
The following pull requests are currently test merged:
#6478: '[DNM] Revert "[MIRROR] Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount"' by Useroth at commit a462568ea5
#6995: '[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again' by Seris02 at commit 15f9b2dfc5
#7173: 'Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"' by Funce at commit d70ef855e8
#6943: 'The final nail in the unfun round removal coffin' by Gandalf2k15 at commit ea55a0d8b6
#6928: '[MODULAR] New species: Ghouls' by linnpap at commit 2458d5008e
#3255: 'Sizeplay v 0.5' by Useroth at commit 08e7778fd5

## Reproduction:
Be AI
Hear erp in xenobiology
Cry

# No but really

What I suspect is that the xenobiology camera is receiving these emote signals and sending them to the AI as the code thinks the AI is the one operating the camera. I'm usually nowhere near witnessing Xenobiology when it happens so I suspect that this is what is happening.

**Comment by SpookyTheFox** [comment] 2021-07-31 07:11
It comes from DS-2 as well, the AI gets all the slime and monkey interactions from xenobio in there.

**Comment by tf-4** [comment] 2021-08-21 20:02
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/7394

**Closed as completed by tf-4** 2021-08-21 20:02 UTC
Labels: Bug
