### ISSUE TITLE
Roundstart and Latejoin Cyborgs do not correctly sync to AI

### ISSUE THREAD

**Issue by SarmentiCampbell** [Skyrat-SS13/Skyrat-TG#16369] opened 2022-09-22 10:00 UTC
## Reproduction:
Just join as a cyborg, they're still correctly linked to the AI but they do not get the Law syncs

**Comment by Zergspower** [comment] 2022-10-03 23:35
DUplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/15807

**Closed as completed by Zergspower** 2022-10-03 23:35 UTC
