### ISSUE TITLE
Can't load the shotgun on Delta station

### ISSUE THREAD

**Issue by sweetsoulbro** [Skyrat-SS13/Skyrat-TG#9075] opened 2021-10-27 06:22 UTC
Reporting client version: 514.1566

## Round ID:
3427

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TESTMERGE ONLY] Telecrystal increased from 35 to 60 for 1 week.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9052)
- [[TESTMERGE ONLY] Haha, very funny. The Ancient Toolbox is 27 TC for the duration of the 60 TC test.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9053)
- [[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8960)

**Comment by YakumoChen** [comment] 2021-10-30 00:03
needs more context, like what shotgun you used, if you unloaded it first, etc

**Comment by tf-4** [comment] 2021-11-01 00:07
duplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/7752

**Closed as completed by tf-4** 2021-11-01 00:07 UTC
