### ISSUE TITLE
Give Bug

### ISSUE THREAD

**Issue by Primie-Problems** [Skyrat-SS13/Skyrat-tg#5247] opened 2021-04-27 02:22 UTC
Reporting client version: 513.1542

## Round ID:
1506

## Reproduction:

Bug: When given items, sometimes the give option remains and cause the option to still appear on your screen, despite you already have the object.

Prompt would be spammed in chat _You moved out of range of Player-Name_ whenever moving.

**Comment by maxymax13** [comment] 2021-04-27 06:02
upstream problem, offer code is like completely broken in general

**Comment by tf-4** [comment] 2022-01-28 17:40
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/3044

**Closed as completed by tf-4** 2022-01-28 17:40 UTC
Labels: Bug, DEVCON 4, TG Upstream Issue
