### ISSUE TITLE
The AI can see ERP emotes in dorms despite 0 camera coverage inside.

### ISSUE THREAD

**Issue by BurgerLUA** [Skyrat-SS13/Skyrat-tg#7489] opened 2021-08-10 08:37 UTC
Reporting client version: 514.1561

## Round ID:
2652

## Testmerges:
- [Revert "[MIRROR] Use rust-g to url_encode (and other builtin overrides)"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7173)
- [[NON-MODULAR] Runtime Begone](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7357)
- [Nanotrasen Fleet Command Expansion](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7418)
- [Ports pollution from Horizon - Original PR: https://github.com/hrzntal/horizon/pull/468 (Made by Azarak)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7453)
- [[MODULAR] New species: Ghouls](https://github.com/Skyrat-SS13/Skyrat-tg/pull/6928)

## Reproduction:

Be AI.
Move to security because someone said something.
On the way, catch a random me emote from dorms.
Your entire chatlog is flooded with 3 paragraphs of ERP.
I have no eyes but I must cry.

**Comment by tf-4** [comment] 2021-08-21 20:01
dupe of https://github.com/Skyrat-SS13/Skyrat-tg/issues/7394

**Closed as completed by tf-4** 2021-08-21 20:01 UTC
Labels: Bug
