### ISSUE TITLE
IPC's / Synths cant be force healed by any means

### ISSUE THREAD

**Issue by Zergspower** [Skyrat-SS13/Skyrat-TG#17939] opened 2022-12-06 07:45 UTC
Reporting client version: 514.1589

## Round ID:
7150

Pretty sure this PR broke it as for some reason we didnt put back in the synthetic code in living.dm

![image](https://user-images.githubusercontent.com/22140677/205851300-a45b9b70-2cb4-482b-bb7e-e6841a81cb6f.png)
https://github.com/Skyrat-SS13/Skyrat-tg/pull/17535

## Testmerges:
- [MOD Hardlight (Refactors how sprite accessories handle MODs)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17372)
- [Moves modular uplink items into a module rather than master files + Removes some of the goofy ahh items we had available to traitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17813)
- [Fairly large assault operatives changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17455)

## Reproduction:

![image](https://user-images.githubusercontent.com/22140677/205850942-9d6a39f6-941d-40d3-ac97-7cf5825ecf63.png)

**Comment by Zergspower** [comment] 2022-12-07 14:02
This also Extends to the SAD, currently reviving synths and IPC's in a non original body isnt possible

**Comment by Floofies** [comment] 2022-12-08 18:23
Caused by tgstation/tgstation#71123

**Comment by Floofies** [comment] 2022-12-11 21:52
I have now fixed this in #18091

**Comment by Floofies** [comment] 2022-12-14 14:28
By fixing this I exposed more severe bugs such as reagents healing robotic bodyparts.
I've now fixed the additional bugs in #18132 and it should be merged / compiled with #18091

**Closed as completed** 2022-12-19 14:29 UTC
Labels: DEVCON 2
