### ISSUE TITLE
desk lamps a bit funky

### ISSUE THREAD

**Issue by Syilumi** [Skyrat-SS13/Skyrat-TG#21407] opened 2023-05-24 16:11 UTC
## Reproduction:
get a desk lamp pick it up and move away from where it originally was, desk lamps'ses light doesn't seem to follow you when you move with it in your hand or equipped

video of how it did because yes
https://github.com/Skyrat-SS13/Skyrat-tg/assets/104273939/06b03758-f599-4906-bda8-3e8cb5928f0f

**Comment by timothymtorres** [comment] 2023-05-25 10:36
Duplicate of [#73557](https://github.com/tgstation/tgstation/issues/73557)

**Comment by Syilumi** [comment] 2023-05-25 16:27
oh whoops

**Closed as not planned** 2023-05-25 16:27 UTC
