### ISSUE TITLE
NorthStar Elevator Floors are Mislabelled because we have one extra CentCom Z-Level

### ISSUE THREAD

**Issue by GoldenAlpharex** [Skyrat-SS13/Skyrat-TG#21821] opened 2023-06-14 02:49 UTC
Reporting client version: 514.1589

## Round ID:
8634

## Testmerges:
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [TTS usage check](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21296)
- [[TM] (Maybe) fixes enormous RSC bloat](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360)
- [[Semi-modular] (The big) Akula species revamp](https://github.com/Skyrat-SS13/Skyrat-tg/pull/20131)
- [Increased alcohol/nicotine tolerance](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21546)
- [[test] more clarity for rails, make rails take longer to connect](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21777)
- [restrict imbuing to ashwalkers & icecats](https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708)

## Reproduction:

This is the reason, it should make it easier to find it in the code knowing that, I'm tired but I don't want to forget, especially if anyone else wants to fix it.

**Comment by lessthnthree** [comment] 2023-06-15 02:03
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20115

**Comment by lessthnthree** [comment] 2023-06-15 17:36
Closing as duplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/19343

**Closed as not planned by lessthnthree** 2023-06-15 17:36 UTC
Labels: wontfix
