### ISSUE TITLE
Paper doesn't visually show up on airlocks when you pin it to them

### ISSUE THREAD

**Issue by Mithrun** [Skyrat-SS13/Skyrat-TG#11150] opened 2022-01-30 19:10 UTC
## Round ID: 
4370

## Reproduction:

If you pin a piece of paper to an airlock you can't see it so people wouldn't really know to examine the airlock and read it.

**Comment by malleyeno** [comment] 2022-02-20 01:44
I was not able to reproduce this bug on the latest merge of the Master branch. Unless there's a specific type of airlock that I missed.

![image](https://user-images.githubusercontent.com/47365670/154825120-9f32b2ea-a826-4d82-a377-b5605db71fcd.png)

**Comment by malleyeno** [comment] 2022-02-20 01:51
Also was not able to reproduce using the glass airlocks or the 'critical' variety.

![image](https://user-images.githubusercontent.com/47365670/154825292-be225d4e-4bf0-4881-a1b4-67055902f489.png)

**Comment by Tastyfish** [comment] 2022-03-17 23:15
Was actually fixed by #11853
Was previously a combination of an upstream issue and us pointing to outdated dmi's making it worse.

**Comment by Zonespace27** [comment] 2022-03-17 23:16
Fixed by #11853

**Closed as completed by Zonespace27** 2022-03-17 23:16 UTC
