### ISSUE TITLE
Character creation UI doesn't show backpack, jumpsuit, underwear or hair anymore

### ISSUE THREAD

**Issue by Innocent-Fire** [Skyrat-SS13/Skyrat-TG#16079] opened 2022-09-05 20:32 UTC
Reporting client version: 514.1583

## Round ID:
6432

## Testmerges:
- [[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
- [[Tram] New tram, new consequences. Tram collisions actually hurt.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)
- [the ash farming expands](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
- [Fixes events happening too often and blobs being handled outside of dynamic](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15947)
- [Fixes being able to retract an active MODsuit's parts and still be able to use its modules](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15950)
- [[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)

## Reproduction: I cleared cache, re-logged twice but the result is the same. The UI no longer shows the various sprites in the blue boxes next to the character in character creation, including hair. I'd consider this to be a massive bug and only appeared recently.

![ssz](https://user-images.githubusercontent.com/104606051/188509611-33e7d5f4-a414-4157-8d89-c5de2f4f847a.png)

**Comment by YakumoChen** [comment] 2022-09-05 22:26
Duplicate of #16074

**Comment by GoldenAlpharex** [comment] 2022-09-06 19:01
I already know what the issue is, should hopefully be fixed from next round onward (and this is a duplicate issue anyway).

**Closed as completed by GoldenAlpharex** 2022-09-06 19:01 UTC
