### ISSUE TITLE
Languages Menu is fucked (California moment?)

### ISSUE THREAD

**Issue by Socialistion** [Skyrat-SS13/Skyrat-TG#12161] opened 2022-03-18 07:24 UTC
So, as the title states, I can't select any languages in the language menu, either to learn or forget them. No idea what's cause this but it just suddenly happened to me. I don't want to be Californian please help me

Reporting client version: 514.1582

## Round ID:
4784

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[TM-ONLY] Disables speech circuit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [[SEMI-MODULAR] Medical Smartdarts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)

**Comment by YakumoChen** [comment] 2022-03-19 03:53
possible duplicate of #11758 ?

**Comment by Zergspower** [comment] 2022-10-03 22:52
Resolved in current version

**Closed as completed by Zergspower** 2022-10-03 22:52 UTC
