### ISSUE TITLE
Lavaland plants unable to be harvested

### ISSUE THREAD

**Issue by Erokusan** [Skyrat-SS13/Skyrat-TG#14842] opened 2022-07-10 11:46 UTC
Reporting client version: 514.1582

## Round ID:
5921

## Testmerges:
- [[MODULAR] Status Indicators with Preference](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529)
- [Database revision revert](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [The Refactaur](https://github.com/Skyrat-SS13/Skyrat-tg/pull/13848)
- [Fleshmind [PRE-RELEASE FINAL]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14023)
- [Temporarily reverts the recent bust changes as per request](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14601)
- [[DNM] [TM ONLY] Revert "[MIRROR] The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review????? [MDB IGNORE]"](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14593)

**Comment by Jolly-66** [comment] 2022-07-10 13:33
Dupe of #14697

**Comment by Jolly-66** [comment] 2022-07-10 17:10
Upstream issue, see https://github.com/tgstation/tgstation/issues/68158

**Closed as completed by Jolly-66** 2022-07-10 17:10 UTC
Labels: TG Upstream Issue
