### ISSUE TITLE
Headset channels reset when you equip the headset

### ISSUE THREAD

**Issue by Microvolnovka19** [Skyrat-SS13/Skyrat-TG#10240] opened 2021-12-24 11:12 UTC
## Round ID:

Tested not on skyrat, but on it's latest build.

## Testmerges:

Dunno

## Reproduction:

Headset channels reset when you equip/unequip the headset(automatically turn off/on to the default settings)

![image](https://user-images.githubusercontent.com/59139863/147347977-b2f4738b-ccba-4df1-b397-4059372fd575.png)
![image](https://user-images.githubusercontent.com/59139863/147347992-8ac3ded8-f927-471b-88a6-d523f60e0b53.png)

**Comment by tf-4** [comment] 2021-12-25 13:27
Duplicate of https://github.com/Skyrat-SS13/Skyrat-tg/issues/10225

**Closed as completed** 2021-12-25 13:27 UTC
