### ISSUE TITLE
Makarov/9x25mm pistol magazine sprites are invisible

### ISSUE THREAD

**Issue by Ruediger4** [Skyrat-SS13/Skyrat-TG#19967] opened 2023-03-18 23:16 UTC
Reporting client version: 514.1588

## Round ID:
7896

## Testmerges:
- [Replace Chaos Event System with ICES - Intensity Credit Event System](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19505)
- [Antag Revamp*: The Nuclear-ish Option](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
- [You can no longer see the icon of languages you don't know](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17248)
- [[TM ONLY] Disables Sideplane, Makes the Game Playable](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19308)
- [[TM-ONLY] Prevents the psyker pirate variant from rolling](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
- [[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler (I can't think of an eyecatching title for demis alright?)](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18364)

## Reproduction:

Quite literally just either spawn a /magazine/m9mm or unload a Makarov. Sprite's invisible.

**Comment by Jolly-66** [comment] 2023-03-30 14:41
Dupe of #19905, also being fixed by #20150

**Closed as completed by Jolly-66** 2023-03-30 14:41 UTC
Labels: Sprites
