### ISSUE TITLE
Cybernetic Heart/EMP Interactions

### ISSUE THREAD

**Issue by CMDR-Gungnir** [Skyrat-SS13/Skyrat-TG#12502] opened 2022-04-02 10:35 UTC
I've run into this a couple times in the last few days, and I forgot to Issue Report it last night, so I've cut out the previous section of the issue report;

## Reproduction:

There are a couple of issues here.

Sometimes the EMP just does nothing to you.

1) Have a Cybernetic Heart
2) Get EMP'd
3) Notice your suit sensors get destroyed, radio fucked with, flash in belt destroyed, Disabler losing charge, stun baton losing some of its uses
4) Notice that you're still standing and your heart isn't affected?
5) Assume your config got fucked with and go fight the EMP mold
6) Get EMP'd and nearly die.

However arguably even more weirdly, sometimes your heart DOES get EMP'd but you're still fine.

1) Have a Cybernetic Heart
2) Get EMP'd
3) Get KO'd by it
4) Just kinda...wake up on your own
5) Watch your Heart's health drop (through Self-Aware)
6) Watch your Heart become Non-Functional
7) Continue to just kinda...walk around? Completely unaffected?

**Comment by YakumoChen** [comment] 2022-04-05 23:26
EMP only has a chance to affect cyberorgans, so this is not a bug. The success rate is dependent on the tier of organ as well.

Dead cyberorgans working as intended is a bug however, but I believe it us an upstream bug.

**Comment by CMDR-Gungnir** [comment] 2022-04-06 03:25
> EMP only has a chance to affect cyberorgans, so this is not a bug. The success rate is dependent on the tier of organ as well.
> 
> Dead cyberorgans working as intended is a bug however, but I believe it us an upstream bug.

Huh- fair enough. I just remember in the past it ALWAYS hit me, and cybernetic limbs always landing the stun, especially since the one chooseable in Character Prefs is a basic.

But if the only bug found here is one that's Probably An Upstream, should I just go ahead and close this?

**Comment by YakumoChen** [comment] 2022-04-06 20:50
Standard cyberhearts have only a 40% chance of crippling EMP effects

Cyberlimbs are different code than organs. They are always affected by EMPs AFAIK, at least the basic ones (which are meant to be trash)

I would close this and report the problems upstream on the tg codebase.

**Closed as completed** 2022-04-07 03:00 UTC
